@extends('admin.layout.forms.edit.index')
@section('action' , "knowledge_area_questions/$item->id")
@section('title' , trans('language.edit'))
@section('page-title',trans('language.edit'))
@section('form-groups')
    @includeIf('admin.components.form.edit.file', ['icon' => 'fa fa-check','label' => trans('language.question_image'),'name'=>'question_image', 'max'=>'2'])
    @includeIf('admin.components.form.edit.file', ['icon' => 'fa fa-check','label' => trans('language.justification_image'),'name'=>'justification_image', 'max'=>'2'])
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.name_ar'),'name'=>'name_ar', 'placeholder'=>trans('language.name_ar')])
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.name_en'),'name'=>'name_en', 'placeholder'=>trans('language.name_en')])
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.justification_ar'),'name'=>'justification_ar', 'placeholder'=>trans('language.justification_ar')])
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.justification_en'),'name'=>'justification_en', 'placeholder'=>trans('language.justification_en')])
    @includeIf('admin.components.form.edit.select', ['label' => trans("language.category"),'name'=>'knowledge_area_id', 'items'=> \App\Knowledge_area::all() , 'icon' => 'fa fa-list',])
@endsection
@section('submit-button-title' , "Edit knowledge Area")
