@extends('admin.layout.forms.add.index')
@section('action' , "flash_cards_items")
@section('title' , trans('language.add'))
@section('page-title',trans('language.flash_cards_items'))
@section('form-groups')
    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-user','label' => trans('language.question_ar'),'name'=>'key_ar', 'placeholder'=>trans('language.question_ar')])
    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-user','label' => trans('language.question_en'),'name'=>'key_en', 'placeholder'=>trans('language.question_en')])
    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-user','label' => trans('language.answer_ar'),'name'=>'value_ar', 'placeholder'=>trans('language.answer_ar')])
    @includeIf('admin.components.form.add.text', ['icon' => 'fa fa-user','label' => trans('language.answer_en'),'name'=>'value_en', 'placeholder'=>trans('language.answer_en')])
    @includeIf('admin.components.form.add.select', ['label' => trans("language.category"),'name'=>'flash_card_id', 'items'=> \App\Flash_card::all() , 'icon' => 'fa fa-list',])
@endsection
@section('submit-button-title' , trans('language.add'))
