@extends('admin.layout.forms.edit.index')
@section('action' , "flash_cards_items/$item->id")
@section('title' , trans('language.edit'))
@section('page-title',trans('language.edit'))
@section('form-groups')
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.key_ar'),'name'=>'key_ar', 'placeholder'=>trans('language.key_ar')])
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.key_en'),'name'=>'key_en', 'placeholder'=>trans('language.key_en')])
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.value_ar'),'name'=>'value_ar', 'placeholder'=>trans('language.value_ar')])
    @includeIf('admin.components.form.edit.text', ['icon' => 'fa fa-user','label' => trans('language.value_en'),'name'=>'value_en', 'placeholder'=>trans('language.value_en')])
    @includeIf('admin.components.form.edit.select', ['label' => trans("language.category"),'name'=>'flash_card_id', 'items'=> \App\Flash_card::all() , 'icon' => 'fa fa-list',])
@endsection
@section('submit-button-title' , "Edit User")
